### ISSUE TITLE
How to combine the sliced image?

### ISSUE THREAD

**Issue by vgthengane** [acl21/image_bbox_slicer#12]
After passing through the object detection model how to get the original image back with predicted coordinated for each object?

**Comment by acl21** [comment]
Merging the slices back to the original image with their coordinates extrapolated to the original image size is a hard task in itself. Definitely out of the scope of this tool. 

Unfortunately, I do not have that time on my hands to write code for that now. But I will keep this feature in mind, perhaps for a later update. Because I think, merging logic is easier than slicing logic so it shouldn't be as hard. Anyways, thanks for stopping by. 👍

**Comment by acl21** [comment]
I take back what I said. While merging sliced images is fairly easy, merging sliced box annotations back to "the original" annotation is incredibly hard. Fives minutes on a drawing board was enough for me to completely drop the idea. Please let me know if you figured out an efficient way to do it.
